import type { Round, TopicOption } from './types'

/** The topics and drawing prompts available in the game. */
export const topicOptions: TopicOption[] = [
  {
    id: 'animals',
    topic: 'Animals',
    topicEmoji: '🐾',
    prompts: [
      'Elephant',
      'Giraffe',
      'Penguin',
      'Butterfly',
      'Octopus',
      'Lion',
      'Tiger',
      'Zebra',
      'Kangaroo',
      'Koala',
      'Panda',
      'Dolphin',
      'Whale',
      'Shark',
      'Crocodile',
      'Turtle',
      'Frog',
      'Owl',
      'Eagle',
      'Flamingo',
      'Peacock',
      'Parrot',
      'Chicken',
      'Rabbit',
      'Squirrel',
      'Hedgehog',
      'Fox',
      'Wolf',
      'Bear',
      'Polar bear',
      'Camel',
      'Hippopotamus',
      'Rhinoceros',
      'Gorilla',
      'Monkey',
      'Sloth',
      'Seal',
      'Walrus',
      'Seahorse',
      'Starfish',
      'Crab',
      'Lobster',
      'Snail',
      'Ladybug',
      'Bee',
      'Spider',
      'Bat',
      'Moose',
      'Reindeer',
      'Chameleon',
    ],
    description: 'Furry, feathered, and wildly fun.',
    color: '#ff8f3f',
  },
  {
    id: 'movies',
    topic: 'Movies',
    topicEmoji: '🎬',
    prompts: [
      'Titanic',
      'Jurassic Park',
      'Finding Nemo',
      'The Lion King',
      'Ghostbusters',
      'The Wizard of Oz',
      'Star Wars',
      'E.T.',
      'Back to the Future',
      'Home Alone',
      'The Matrix',
      'King Kong',
      'Spider-Man',
      'Batman',
      'Superman',
      'Frozen',
      'Toy Story',
      'Shrek',
      'Up',
      'Cars',
      'Ratatouille',
      'WALL-E',
      'Inside Out',
      'Monsters, Inc.',
      'The Incredibles',
      'Moana',
      'Aladdin',
      'Beauty and the Beast',
      'The Little Mermaid',
      'Cinderella',
      'Snow White',
      'Mary Poppins',
      'The Jungle Book',
      'Pirates of the Caribbean',
      'Indiana Jones',
      'Rocky',
      'Jaws',
      'Avatar',
      'Gladiator',
      'The Terminator',
      'Mission: Impossible',
      'Men in Black',
      'The Mask',
      'Edward Scissorhands',
      'Charlie and the Chocolate Factory',
      'The Nightmare Before Christmas',
      'How to Train Your Dragon',
      'Kung Fu Panda',
      'Ice Age',
      'Despicable Me',
    ],
    description: 'Iconic films made for the drawing board.',
    color: '#ff5d8f',
  },
  {
    id: 'books',
    topic: 'Books',
    topicEmoji: '📚',
    prompts: [
      'Alice in Wonderland',
      'The Little Prince',
      'Treasure Island',
      'The Very Hungry Caterpillar',
      'Harry Potter',
      'The Cat in the Hat',
      "Charlotte's Web",
      'Winnie-the-Pooh',
      'Peter Pan',
      'The Jungle Book',
      'The Wizard of Oz',
      'The Hobbit',
      'The Lord of the Rings',
      'The Chronicles of Narnia',
      'Percy Jackson',
      'Diary of a Wimpy Kid',
      'Matilda',
      'Charlie and the Chocolate Factory',
      'James and the Giant Peach',
      'The BFG',
      'Fantastic Mr Fox',
      'The Gruffalo',
      'Where the Wild Things Are',
      'The Giving Tree',
      'Green Eggs and Ham',
      'Goodnight Moon',
      'The Snowy Day',
      'The Secret Garden',
      'Black Beauty',
      'Anne of Green Gables',
      'Little Women',
      'Heidi',
      'The Wind in the Willows',
      'The Tale of Peter Rabbit',
      'Pinocchio',
      'Robin Hood',
      'Robinson Crusoe',
      "Gulliver's Travels",
      'Moby-Dick',
      'Twenty Thousand Leagues Under the Sea',
      'Around the World in Eighty Days',
      'The Time Machine',
      'The War of the Worlds',
      'A Christmas Carol',
      'The Adventures of Sherlock Holmes',
      'The Adventures of Tom Sawyer',
      'The Velveteen Rabbit',
      'Curious George',
      'The Rainbow Fish',
      'Captain Underpants',
    ],
    description: 'Beloved stories and literary adventures.',
    color: '#38bdf8',
  },
  {
    id: 'english-idioms',
    topic: 'English idioms',
    topicEmoji: '💬',
    prompts: [
      'Break the ice',
      'Piece of cake',
      'Raining cats and dogs',
      'Spill the beans',
      'Hit the nail on the head',
      'Hold your horses',
      'Let the cat out of the bag',
      'Bite the bullet',
      'Under the weather',
      'Cost an arm and a leg',
      'When pigs fly',
      'A fish out of water',
      'The elephant in the room',
      'Barking up the wrong tree',
      'Burn the midnight oil',
      'Cry over spilled milk',
      'Put all your eggs in one basket',
      'A storm in a teacup',
      'Butterflies in your stomach',
      'Have your head in the clouds',
      'Keep your chin up',
      'Jump on the bandwagon',
      'Go the extra mile',
      "Pull someone's leg",
      'See eye to eye',
      'Sit on the fence',
      'Take it with a grain of salt',
      'The ball is in your court',
      'Throw in the towel',
      'Walk on eggshells',
      'Wild goose chase',
      'Add fuel to the fire',
      'Beat around the bush',
      'Bite off more than you can chew',
      'Burn bridges',
      'Catch someone red-handed',
      'Cross that bridge when you come to it',
      'Cut corners',
      'Get cold feet',
      'Give someone the cold shoulder',
      'Hit the sack',
      'In the same boat',
      'Keep an eye on it',
      'Miss the boat',
      'On thin ice',
      'Put your foot in your mouth',
      "Steal someone's thunder",
      'Take the bull by the horns',
      'The tip of the iceberg',
      'Turn a blind eye',
    ],
    description: 'Familiar phrases with literal twists.',
    color: '#a78bfa',
  },
  {
    id: 'places-landmarks',
    topic: 'Places/Landmarks',
    topicEmoji: '🗺️',
    prompts: [
      'Eiffel Tower',
      'Great Wall of China',
      'Taj Mahal',
      'Statue of Liberty',
      'Pyramids of Giza',
      'Big Ben',
      'Sydney Opera House',
      'Golden Gate Bridge',
      'Leaning Tower of Pisa',
      'Colosseum',
      'Machu Picchu',
      'Christ the Redeemer',
      'Mount Rushmore',
      'Stonehenge',
      'Sphinx',
      'Burj Khalifa',
      'Buckingham Palace',
      'White House',
      'Empire State Building',
      'Tower Bridge',
      'London Eye',
      'Mount Fuji',
      'Mount Everest',
      'Niagara Falls',
      'Grand Canyon',
      'Sahara Desert',
      'Amazon Rainforest',
      'Venice',
      'Times Square',
      'Hollywood Sign',
      'Disneyland',
      'Central Park',
      'Santorini',
      'Great Barrier Reef',
      'Easter Island',
      'Angkor Wat',
      'Petra',
      'Chichen Itza',
      'Mount Kilimanjaro',
      'Serengeti',
      'Louvre Museum',
      'Arc de Triomphe',
      'Brandenburg Gate',
      'Sagrada Familia',
      'Neuschwanstein Castle',
      "St Basil's Cathedral",
      'Forbidden City',
      'Uluru',
      'Table Mountain',
      'Northern Lights',
    ],
    description: 'Famous destinations from around the world.',
    color: '#22c55e',
  },
]

export const defaultTopic = topicOptions[0]

export const initialRound: Round = {
  topic: defaultTopic.topic,
  topicEmoji: defaultTopic.topicEmoji,
  prompt: defaultTopic.prompts[0],
}
